# Generated by Django 2.1.11 on 2019-12-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20191216_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.TextField(default='{}')),
                ('audio_url', models.TextField(default='')),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationItem',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Document')),
                ('start_timestamp', models.TimeField()),
                ('end_timestamp', models.TimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_item', to='api.Conversation')),
            ],
            bases=('api.document',),
        ),
        migrations.CreateModel(
            name='ConversationItemAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(default=0.0)),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_annotation', to='api.ConversationItem')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='s2txtannotation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='s2txtannotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='s2txtannotation',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('Conversations', 'Conversations validation and labelling')], max_length=30),
        ),
        migrations.RenameModel(
            old_name='S2txtProject',
            new_name='ConversationsProject',
        ),
        migrations.DeleteModel(
            name='S2txtAnnotation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.ConversationsProject'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationitemannotation',
            unique_together={('start_offset', 'end_offset', 'label', 'conversation')},
        ),
    ]
