# Generated by Django 2.1.11 on 2019-12-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191218_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='documents',
            new_name='document',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('project', 'document')},
        ),
    ]
