# Generated by Django 2.1.11 on 2019-12-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191217_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='audio_file',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='conversationitem',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_items', to='api.Conversation'),
        ),
        migrations.RemoveField(
            model_name='conversationitem',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='conversationitem',
            name='start_timestamp',
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='end_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='start_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='machine_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
