# Generated by Django 2.1.11 on 2019-12-18 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191218_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationItem',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Document')),
                ('start_timestamp', models.TimeField()),
                ('end_timestamp', models.TimeField()),
            ],
            bases=('api.document',),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_item', to='api.Conversation'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='document',
        ),
    ]
