# Generated by Django 2.1.11 on 2019-12-18 17:17

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('api', 'Document')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0004_auto_20191218_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='document',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.document_set+', to='contenttypes.ContentType'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
