# Generated by Django 2.1.11 on 2019-12-18 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0004_auto_20191218_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='conversationitem',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='conversationitem',
            name='start_timestamp',
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='end_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='machine_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='start_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.document_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='conversationitem',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_items', to='api.Conversation'),
        ),
    ]
