# Generated by Django 2.1.11 on 2019-12-18 17:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20191218_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationItemAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(default=0.0)),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_annotations', to='api.Document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='conversation',
            name='audio_file',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='conversationitemannotation',
            unique_together={('start_offset', 'end_offset', 'label', 'document')},
        ),
    ]
