# Generated by Django 2.1.11 on 2019-12-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191218_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationitem',
            name='text_validated',
            field=models.BooleanField(default=False),
        ),
    ]
