# Generated by Django 2.1.11 on 2019-12-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversationitem_text_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='meta',
            field=models.TextField(default='{}'),
        ),
    ]
