# Generated by Django 2.1.11 on 2020-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191220_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationitem',
            old_name='text_validated',
            new_name='is_validated',
        ),
        migrations.AddField(
            model_name='conversationitem',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
